## This document contains instructions for a new Kubernetes YAML that needs to be created,
## and the resultant YAML.
##
## The structure of the document is as follows:
## 1. Description of the desired YAML
## 2. The new YAML, terminated by an 'EOF'

## 1. Instructions for the new Kubernetes YAML:
create a deployment which pulls a Jupyter Notebook image and requests 1 GPU resource

## 2. The new YAML:
---
apiVersion: v1
kind: Service
metadata:
  name: jupyterlab-notebook
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: jupyterlab-notebook
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jupyterlab-notebook
  namespace: default
spec:
  replicas: 1
  selector:
   