name: kindTest 

env: 
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  APP_NAME: demo # CHANGE TO DESIRED APP NAME
  IMAGE_TAGS: latest ${{ github.sha }}

  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: "copilot-ops" # CHANGE TO DESIRED NAMESPACE

  APP_PORT: "8080"

on:
  # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
  pull_request:
    branches: [ main ]

jobs:
  build-and-push: 
    name: Build and push to github container registry
    runs-on: ubuntu-22.04
    environment: development

    outputs:
        ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
        SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v2

    - name: Kind Cluster
      # You may pin to the exact commit or the version.
      # uses: helm/kind-action@9e8295d178de23cbfbd8fa16cf844eec1d773a07
      uses: helm/kind-action@v1.4.0

    - run: kubectl apply -f generated-by-copilot-ops/
    
